// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (
    project_id,
    name,
    storage_path,
    tags,
    created_by
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, project_id, name, description, storage_path, tags, status, created_by, created_at, updated_at
`

type CreateAssetParams struct {
	ProjectID   uuid.UUID
	Name        string
	StoragePath string
	Tags        string
	CreatedBy   uuid.UUID
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, createAsset,
		arg.ProjectID,
		arg.Name,
		arg.StoragePath,
		arg.Tags,
		arg.CreatedBy,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.StoragePath,
		&i.Tags,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAssetByName = `-- name: GetAssetByName :one
SELECT id, project_id, name, description, storage_path, tags, status, created_by, created_at, updated_at FROM assets
WHERE name = $1 AND project_id= $2
`

type GetAssetByNameParams struct {
	Name      string
	ProjectID uuid.UUID
}

func (q *Queries) GetAssetByName(ctx context.Context, arg GetAssetByNameParams) (Asset, error) {
	row := q.db.QueryRowContext(ctx, getAssetByName, arg.Name, arg.ProjectID)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Description,
		&i.StoragePath,
		&i.Tags,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAssetStoragePath = `-- name: UpdateAssetStoragePath :exec
UPDATE assets
SET storage_path = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateAssetStoragePathParams struct {
	ID          uuid.UUID
	StoragePath string
}

func (q *Queries) UpdateAssetStoragePath(ctx context.Context, arg UpdateAssetStoragePathParams) error {
	_, err := q.db.ExecContext(ctx, updateAssetStoragePath, arg.ID, arg.StoragePath)
	return err
}
