// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects(id, title, description, created_by, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    NULLIF($2, ''),
    $3,
    NOW(),
    NOW()
)
RETURNING id, title, description, status, created_by, created_at, updated_at
`

type CreateProjectParams struct {
	Title     string
	Column2   interface{}
	CreatedBy uuid.UUID
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.Title, arg.Column2, arg.CreatedBy)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
