// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects(id, title, description, created_by, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    NULLIF($2, ''),
    $3,
    NOW(),
    NOW()
)
RETURNING id, title, description, status, created_by, created_at, updated_at
`

type CreateProjectParams struct {
	Title     string
	Column2   interface{}
	CreatedBy uuid.UUID
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject, arg.Title, arg.Column2, arg.CreatedBy)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectByTitle = `-- name: DeleteProjectByTitle :exec
DELETE FROM projects
WHERE title = $1
`

func (q *Queries) DeleteProjectByTitle(ctx context.Context, title string) error {
	_, err := q.db.ExecContext(ctx, deleteProjectByTitle, title)
	return err
}

const getProjectByTitle = `-- name: GetProjectByTitle :one
SELECT id, title, description, status, created_by, created_at, updated_at FROM projects
WHERE title = $1
`

func (q *Queries) GetProjectByTitle(ctx context.Context, title string) (Project, error) {
	row := q.db.QueryRowContext(ctx, getProjectByTitle, title)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectsForUser = `-- name: GetProjectsForUser :many
SELECT p.id, p.title, p.description, p.status, p.created_by, p.created_at, p.updated_at
FROM projects p
JOIN users_projects up
  ON up.project_id = p.id
WHERE up.user_id = $1
`

func (q *Queries) GetProjectsForUser(ctx context.Context, userID uuid.UUID) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, getProjectsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
