// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_projects.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addNewProjectUser = `-- name: AddNewProjectUser :one
INSERT INTO users_projects(project_id, user_id, user_status)
VALUES(
    $1,
    $2,
    $3
)
RETURNING id, project_id, user_id, user_status
`

type AddNewProjectUserParams struct {
	ProjectID  uuid.UUID
	UserID     uuid.UUID
	UserStatus string
}

func (q *Queries) AddNewProjectUser(ctx context.Context, arg AddNewProjectUserParams) (UsersProject, error) {
	row := q.db.QueryRowContext(ctx, addNewProjectUser, arg.ProjectID, arg.UserID, arg.UserStatus)
	var i UsersProject
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.UserStatus,
	)
	return i, err
}

const getUserProjectRelation = `-- name: GetUserProjectRelation :one
SELECT id, project_id, user_id, user_status FROM users_projects
WHERE user_id = $1 AND project_id = $2
`

type GetUserProjectRelationParams struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetUserProjectRelation(ctx context.Context, arg GetUserProjectRelationParams) (UsersProject, error) {
	row := q.db.QueryRowContext(ctx, getUserProjectRelation, arg.UserID, arg.ProjectID)
	var i UsersProject
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.UserStatus,
	)
	return i, err
}
