// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users_projects.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addNewProjectUser = `-- name: AddNewProjectUser :one
INSERT INTO users_projects(project_id, user_id, user_status)
VALUES(
    $1,
    $2,
    $3
)
RETURNING id, project_id, user_id, user_status
`

type AddNewProjectUserParams struct {
	ProjectID  uuid.UUID
	UserID     uuid.UUID
	UserStatus string
}

func (q *Queries) AddNewProjectUser(ctx context.Context, arg AddNewProjectUserParams) (UsersProject, error) {
	row := q.db.QueryRowContext(ctx, addNewProjectUser, arg.ProjectID, arg.UserID, arg.UserStatus)
	var i UsersProject
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.UserStatus,
	)
	return i, err
}

const getAllProjectUsers = `-- name: GetAllProjectUsers :many
SELECT id, project_id, user_id, user_status FROM users_projects
WHERE project_id = $1
`

func (q *Queries) GetAllProjectUsers(ctx context.Context, projectID uuid.UUID) ([]UsersProject, error) {
	rows, err := q.db.QueryContext(ctx, getAllProjectUsers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsersProject
	for rows.Next() {
		var i UsersProject
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.UserStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserProjectRelation = `-- name: GetUserProjectRelation :one
SELECT id, project_id, user_id, user_status FROM users_projects
WHERE user_id = $1 AND project_id = $2
`

type GetUserProjectRelationParams struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) GetUserProjectRelation(ctx context.Context, arg GetUserProjectRelationParams) (UsersProject, error) {
	row := q.db.QueryRowContext(ctx, getUserProjectRelation, arg.UserID, arg.ProjectID)
	var i UsersProject
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.UserStatus,
	)
	return i, err
}

const removeUserFromProject = `-- name: RemoveUserFromProject :exec
DELETE FROM users_projects
WHERE user_id = $1 AND project_id = $2
`

type RemoveUserFromProjectParams struct {
	UserID    uuid.UUID
	ProjectID uuid.UUID
}

func (q *Queries) RemoveUserFromProject(ctx context.Context, arg RemoveUserFromProjectParams) error {
	_, err := q.db.ExecContext(ctx, removeUserFromProject, arg.UserID, arg.ProjectID)
	return err
}
